=== qiangshi1/learn_xsd/test5.xsd
<?xml version="1.0"?>
<!-- 复合元素 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com" targetNamespace="http://www.w3schools.com" elementFormDefault="qualified">

<xs:complexType name="personinfo"> <!-- 针对复合元素写法二 --> <!-- 定义一个type -->
  <xs:sequence>
    <xs:element name="firstname" type="xs:string"/>
    <xs:element name="lastname" type="xs:string"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="fullpersoninfo">
  <xs:complexContent>
    <xs:extension base="personinfo">
      <xs:sequence>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:element name="note"> <!-- 定义一个element -->
  <xs:complexType>
    <xs:sequence>
      <!-- 定义复合元素 写法一 -->
      <xs:element name="employee">
        <xs:complexType> <!-- 这个其实是一个匿名type -->
          <xs:sequence> <!-- xs:sequence是一个指示器，后续会有讨论 -->
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <!-- 定义复合元素 写法二 -->
      <xs:element name="employee2" type="personinfo"/>
      <!-- 上述的复合元素写法二支持多个元素共用一个type -->
      <xs:element name="employee3" type="personinfo"/>
      <!-- 使用 xs:extension base 实现继承（类似于继承的效果）-->
      <xs:element name="employee4" type="fullpersoninfo"/>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== qiangshi1/learn_xsd/test5.xml
<!-- 复合元素 -->
<!-- 复合元素就是可能包含其他元素/属性的元素 -->
<!-- 有四种复合元素，它们是: 空元素/包含其他元素的元素/仅包含文本的元素/包含元素和文本的元素 -->
<note xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com test5.xsd">
  <!-- product是一个复合元素 -->
  <!-- <product pid="1345"/> -->
  <!-- employee是一个复合元素 -->
  <employee>
    <firstname>John</firstname>
    <lastname>Smith</lastname>
  </employee>
  <employee2>
    <firstname>Zs</firstname>
    <lastname>Ls</lastname>
  </employee2>
  <employee3>
    <firstname>Días</firstname>
    <lastname>Leonardo</lastname>
  </employee3>
  <employee4>
    <firstname>Zhao</firstname>
    <lastname>Si</lastname>
    <address>Notre Dame Cathedral</address>
    <city>Paris</city>
    <country>Franch</country>
  </employee4>
  <!-- food是一个复合元素 -->
  <!-- <food type="dessert">Ice cream</food> -->
  <!-- description是一个复合元素 -->
  <!-- <description>
    It happened on <date lang="norwegian">03.03.99</date> ....
  </description> -->
</note>
